/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AgentServiceRegistry {
  export type ServiceStruct = {
    name: string;
    endpoint: string;
    cost: BigNumberish;
    owner: AddressLike;
  };

  export type ServiceStructOutput = [
    name: string,
    endpoint: string,
    cost: bigint,
    owner: string
  ] & { name: string; endpoint: string; cost: bigint; owner: string };
}

export interface AgentServiceRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "getService" | "registerService" | "services"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "getService", values: [string]): string;
  encodeFunctionData(
    functionFragment: "registerService",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "services", values: [string]): string;

  decodeFunctionResult(functionFragment: "getService", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerService",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "services", data: BytesLike): Result;
}

export interface AgentServiceRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgentServiceRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgentServiceRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getService: TypedContractMethod<
    [_name: string],
    [AgentServiceRegistry.ServiceStructOutput],
    "view"
  >;

  registerService: TypedContractMethod<
    [_name: string, _endpoint: string, _cost: BigNumberish],
    [void],
    "nonpayable"
  >;

  services: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, string] & {
        name: string;
        endpoint: string;
        cost: bigint;
        owner: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getService"
  ): TypedContractMethod<
    [_name: string],
    [AgentServiceRegistry.ServiceStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerService"
  ): TypedContractMethod<
    [_name: string, _endpoint: string, _cost: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "services"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, string] & {
        name: string;
        endpoint: string;
        cost: bigint;
        owner: string;
      }
    ],
    "view"
  >;

  filters: {};
}
